### ISSUE TITLE
קשה לקרוא את הטקסט בחלון

### ISSUE THREAD

**Issue by erelsgl** [Enzo-Gorlami-Games/Hazard#1]
כשהטקסט בחלון, אם השחקן עומד בזוית הלא-נכונה, הוא לא מצליח לקרוא אותו - חלק מהטקסט נחתך. עדיף לשים את טקסט ההסבר בחלון שנמצא במקום קבוע על המסך כך שיוכלו לראות אותו מכל זוית.

**Comment by talzich** [comment]
לצערי לא קיבלתי התראה מגיטהאב על ההערה הזו ובמקרה ראיתי אותה רק היום. כנראה שכבר לא אספיק לתקן את העניין וגם לערוך מחדש את הקדימון, שמכיל את הפיצ'ר הזה.  עם זאת, אנסה לשפר את המשחק גם לאחר ההגשה כחלק מתיק העבודות שאני בונה.
