### ISSUE TITLE
השלב האחרון

### ISSUE THREAD

**Issue by erelsgl** [Enzo-Gorlami-Games/Hazard#2]
יפה מאד, אבל לא הבנתי את השלב האחרון - האם המשימה היא פשוט לשים את המטף ליד התנור?
אם כך, אולי הטקסט בהתחלה צריך להיות שונה, למשל:
Fire is not a bad thing, as long as you have the right equipment to keep it calm

**Comment by talzich** [comment]
החשש שלי הוא שלבים פשוטים מדי לפיתרון. ניסיתי להגיע לאיזון אליו הגיעו משחקי פורטל בו חלק מהכיף הוא לגלות מה צריך לעשות. כרגע הזמן הממוצע לסיום המשחק עומד על 7 דקות כאשר כל שחקני הניסוי, למעט אחד, נכשלו לפחות בשלב אחד. אנסה לשנות את הטקסט ואבחן את ההשפעה על זמן המשחק הממוצע.
